# Generated by Django 4.2 on 2023-04-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_contend',
            new_name='comment_content',
        ),
    ]
