# Generated by Django 4.2 on 2023-04-30 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_rename_comment_contend_comment_comment_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
